# data_dir: # please define your data_dir if your data is not placed at data/
train_json: train.json
img_height: 1080
img_width: 1920
cropped_height: 224
cropped_width: 224
learning_rate: 1e-4
num_epoch: 7
num_workers: 16
milestones: [6, 8]
gamma: 0.1
split_samples_func: prepare_training_samples
batch_size: 1
cam_selected_num: 72
image_pairs_per_batch: 3
data_augmentation: False
triplet_batch_size: 64
triplet_sampling_ratio: [0.5,0.3,0.2] 
## Zoomout ratio ZO ##
zoomout_ratio: [2] 
features_net: FeaturesDeitTiny_P3DE
model_class: TripletNet_cam_pos
loss_func: TripletLoss 
mode: 'Triplet_cam_pos' 
scene_ratio: 1
sum: True
## regularization parameter lambda##
scale: 0.1
## 1/Grid 1/G ##
grid: 60
